# Generated by Django 4.0.4 on 2022-06-04 10:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_unitmodel_form'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitAmount',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('1 MONTH', '1 MONTH'), ('3 MONTHS', '3 MONTHS'), ('6 MONTHS', '6 MONTHS'), ('1 YEAR', '1 YEAR')], default='1 MONTH', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_amounts', to='school.unitmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
