# Generated by Django 4.0.4 on 2022-06-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_invoiceunit_invoice_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='period',
            field=models.IntegerField(blank=True, choices=[('1 MONTH', 30), ('3 MONTHS', 90), ('6 MONTHS', 180), ('1 YEAR', 365)], null=True),
        ),
        migrations.AlterField(
            model_name='unitamount',
            name='period',
            field=models.IntegerField(choices=[('1 MONTH', 30), ('3 MONTHS', 90), ('6 MONTHS', 180), ('1 YEAR', 365)], default=30),
        ),
    ]
