# Generated by Django 4.0.4 on 2022-06-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_subscription_period_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_created']},
        ),
    ]
