# Generated by Django 4.0.4 on 2022-06-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_invoice_options_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-date_created']},
        ),
    ]
