# Generated by Django 4.0.4 on 2022-06-18 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_subscription_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceunit',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_unit_set', to='payments.invoice'),
        ),
    ]
