# Generated by Django 4.0.4 on 2022-07-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_subjectamount_formamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
