# Generated by Django 4.0.4 on 2022-07-10 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_invoice_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
