# Generated by Django 4.0.4 on 2022-07-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_commission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-date_created']},
        ),
    ]
