# Generated by Django 4.0.4 on 2022-05-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_publicuser_options_alter_staff_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicuser',
            name='is_password_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_password_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
