# Generated by Django 4.0.4 on 2022-05-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_publicuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicuser',
            name='is_password_verified',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_password_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='is_password_verified',
            field=models.BooleanField(default=False),
        ),
    ]
