# Generated by Django 4.0.4 on 2022-07-06 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_agent_user_email_verified_user_is_agent_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='status',
            new_name='profile_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='county',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DEACTIVATED', 'DEACTIVATED'), ('SUSPENDED', 'SUSPENDED')], default='ACTIVE', max_length=255),
        ),
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school', models.CharField(blank=True, max_length=1000, null=True)),
                ('profile_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DEACTIVATED', 'DEACTIVATED'), ('SUSPENDED', 'SUSPENDED')], default='ACTIVE', max_length=255)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='county_users', to='users.county')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
