# Generated by Django 4.0.4 on 2022-07-08 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_agent_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='agent_subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AgentUser',
        ),
    ]
