# Generated by Django 4.0.4 on 2022-06-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationcodes',
            old_name='id_number',
            new_name='id_no',
        ),
    ]
