# Generated by Django 4.0.4 on 2022-06-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_id_number_registrationcodes_id_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcodes',
            name='users',
            field=models.BigIntegerField(default=0),
        ),
    ]
