# Generated by Django 4.0.4 on 2022-05-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
