# Generated by Django 4.0.4 on 2022-05-21 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_formmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmodel',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_units', to='school.formmodel'),
        ),
    ]
