# Generated by Django 4.0.4 on 2022-07-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_covervideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='school.unitmodel'),
        ),
    ]
