# Generated by Django 4.0.4 on 2022-07-15 07:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_videomodel_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitmodel',
            name='form',
        ),
        migrations.RemoveField(
            model_name='unitmodel',
            name='subject',
        ),
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_units', to='school.formmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_units', to='school.subjectmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='unitmodel',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_units', to='school.topicmodel'),
        ),
    ]
