# Generated by Django 4.0.4 on 2022-07-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_topicmodel_form_alter_topicmodel_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicmodel',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='index',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
