# Generated by Django 4.0.4 on 2022-07-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_topicmodel_options_topicmodel_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmodel',
            name='index',
            field=models.BigIntegerField(default=0),
        ),
    ]
