# Generated by Django 4.0.4 on 2022-07-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_topicmodel_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitmodel',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='unitmodel',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
