from django.urls import path
from staff import views

urlpatterns = [
    path("admin", views.Admin.as_view()),
    path("admin/videos", views.ListVideos.as_view()),
    path("admin/videos/add-video", views.AddVideo.as_view()),
    path("admin/videos/cover-video", views.CoverVideo.as_view()),
    path("admin/videos/cover-video-id", views.cover_videoid),
    path("admin/videos/add-video-id", views.add_videoid),
    path("admin/forms", views.ListForm.as_view()),
    path("admin/update-form", views.UpdateForm.as_view()),
    path("admin/update-subject", views.UpdateSubject.as_view()),
    path("admin/delete-form", views.delete_form),
    path("admin/forms/add-form", views.AddForm.as_view()),
    path("admin/subjects", views.ListSubjects.as_view()),
    path("admin/delete-subject", views.delete_subject),
    path("admin/subjects/add-subject", views.AddSubject.as_view()),
    path("admin/units", views.ListUnits.as_view()),
    path("admin/delete-unit", views.delete_unit),
    path("admin/units/add-unit", views.AddUnit.as_view()),
    path("admin/units/view", views.UnitDetailView.as_view()),
    path("admin/payments/invoices", views.ListInvoices.as_view()),
    path("admin/payments/transactions", views.ListTransactions.as_view()),
    path("admin/subscriptions/active", views.ListCurrentSubscription.as_view()),
    path("admin/subscriptions/expired", views.ListExpiredSubscriptions.as_view()),
    path("admin/subscriptions/revoked", views.ListRevokedSubscriptions.as_view()),
    path("admin/counties", views.ListCounties.as_view()),
    path("admin/counties/add-county", views.AddCounty.as_view()),
    path("admin/payments/unit-amount", views.AddUnitAmountView.as_view()),
    path("admin/agents", views.ListAgents.as_view()),
    path("admin/agents/add-agent", views.AddAgent.as_view()),
    path("admin/agents/<pk>", views.AgentDetails.as_view()),
    path("admin/subjects/<pk>", views.RetrieveSubject.as_view(), name="retrieve_subjects"),
    path("admin/payments/add-amount", views.AddSubjectAmountView.as_view()),
    path("admin/forms/<pk>", views.RetrieveForm.as_view()),
    path("admin/payments/add-form-amount", views.AddFormAmountView.as_view()),
    path("admin/users", views.ListUsers.as_view()),
    path("admin/payments/agent-commission", views.ListAgentCommission.as_view()),
    path("admin/payments/add-agent-commission", views.AddAgentCommission.as_view()),
    path("admin/payments/delete-agent-commission", views.delete_commission)
]
