# Generated by Django 4.0.4 on 2022-05-31 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('send_to', models.CharField(max_length=500)),
                ('code', models.CharField(blank=True, max_length=500, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('REVOKED', 'REVOKED')], default='PENDING', max_length=255)),
            ],
        ),
    ]
